name: projectfrontend
description: A new Flutter project.

publish_to: 'none' # Remove this line if you're publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # You might need to update this to ">=3.0.0 <4.0.0" if latest Firebase requires it

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^19.4.0 # Updated
  fl_chart: ^1.0.0                     # Updated
  provider: ^6.1.1
  http: ^1.1.2
  intl: ^0.20.2                       # Updated
  url_launcher: ^6.2.2
  google_fonts: ^6.1.0
  firebase_core: ^4.0.0               # Updated
  firebase_auth: ^6.0.0               # Updated
  # firebase_auth_web: ^5.8.13        # REMOVE THIS LINE. It should be pulled transitively by firebase_auth
  cloud_firestore: ^6.0.0             # Updated
  firebase_storage: ^13.0.0           # Updated
  firebase_database: ^12.0.0          # Updated
  firebase_messaging: ^16.0.0         # Updated
  firebase_analytics: ^12.0.0         # Updated
  firebase_crashlytics: ^5.0.0        # Updated
  firebase_app_check: ^0.4.0          # Updated
  uuid: ^4.3.3
  path_provider: ^2.1.2
  permission_handler: ^12.0.1         # Updated
  cached_network_image: ^3.3.1
  image_cropper: 9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/