name: projectfrontend
description: A new Flutter project.

publish_to: 'none' # Remove this line if you're publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.2.0
  fl_chart: ^0.64.0
  provider: ^6.1.1
  http: ^1.1.2
  intl: ^0.19.0
  url_launcher: ^6.2.2
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_auth_web: ^5.8.10
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6  # Kuhifadhi faili Firebase
  firebase_database: ^10.4.5  # Kuhifadhi data real-time
  firebase_messaging: ^14.7.6  # Push notifications
  firebase_analytics: ^10.6.5  # Analytics kwa Firebase
  firebase_crashlytics: ^3.4.10  # Crash reports kwa Firebase
  firebase_app_check: ^0.2.1+6  # App security kwa Firebase
  uuid: ^4.3.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
    